-- Tabela que registra cada clique em "Encomendar agora" / "Encomendar selecionados".
-- Como aplicar: app.supabase.com > seu projeto > SQL Editor > New query
-- > cole este conteúdo inteiro > Run.

create table if not exists clicks (
  id bigint generated by default as identity primary key,
  product_name text not null,
  section text,
  category text,
  created_at timestamptz default now()
);

alter table clicks enable row level security;

-- Qualquer visitante pode REGISTRAR um clique (é assim que o site conta os pedidos).
create policy "Anyone can log a click"
on clicks for insert
to anon, authenticated
with check (true);

-- Só quem estiver logado (você, no painel admin) pode LER os cliques registrados.
create policy "Only authenticated can read clicks"
on clicks for select
to authenticated
using (true);
